import type { CSSProperties } from "react";
import { OVERLAY_Z_INDEX } from "../constants/ui";

export const editorStyles: Record<string, CSSProperties> = {
  container: {
    display: "grid",
    gap: "0.75rem",
    padding: "1rem",
    border: "1px solid var(--ssml-editor-border)",
    borderRadius: "0.5rem",
    color: "var(--ssml-editor-color)",
    backgroundColor: "var(--ssml-editor-bg)",
  },
  toolbarContainer: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  toolbarActions: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  toolbarSeparator: {
    width: "1px",
    height: "2.25rem",
    margin: "0 0.25rem",
    backgroundColor: "var(--ssml-editor-border)",
  },
  toolbarDropdown: {
    position: "relative",
    display: "inline-block",
  },
  toolbarSwitch: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.375rem",
    minHeight: "2.25rem",
    color: "var(--ssml-editor-color)",
    font: "inherit",
  },
  toolbarSwitchTrack: {
    display: "inline-flex",
    alignItems: "center",
    width: "2.75rem",
    height: "1.5rem",
    padding: "0.1875rem",
    border: 0,
    borderRadius: "999px",
    backgroundColor: "var(--ssml-editor-control-border)",
    cursor: "pointer",
    font: "inherit",
    transition: "background-color 0.2s ease",
  },
  toolbarSwitchThumb: {
    width: "1.125rem",
    height: "1.125rem",
    borderRadius: "50%",
    backgroundColor: "var(--ssml-editor-bg)",
    transition: "transform 0.2s ease",
  },
  toolbarButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.375rem",
    minHeight: "2.25rem",
    padding: "0.375rem 0.625rem",
    border: "1px solid var(--ssml-editor-control-border)",
    borderRadius: "0.25rem",
    color: "var(--ssml-editor-color)",
    backgroundColor: "var(--ssml-editor-control-bg)",
    font: "inherit",
    cursor: "pointer",
  },
  toolbarButtonActive: {
    border: "1px solid var(--ssml-editor-active-border)",
    backgroundColor: "var(--ssml-editor-active-bg)",
  },
  display: {
    display: "grid",
    gap: "0.5rem",
  },
  toolbarIconOnly: {
    justifyContent: "center",
    minWidth: "2.25rem",
    padding: "0.375rem",
  },
  toolbarIcon: {
    display: "inline-flex",
    width: "1.25rem",
    justifyContent: "center",
    fontSize: "1.1rem",
    lineHeight: 1,
  },
  toolbarChevron: {
    fontSize: "0.7rem",
    lineHeight: 1,
  },
  toolbarMenu: {
    position: "fixed",
    zIndex: OVERLAY_Z_INDEX,
    display: "grid",
    minWidth: "max-content",
    maxHeight: "min(24rem, calc(100vh - 1rem))",
    gap: "0.125rem",
    padding: "0.25rem",
    border: "1px solid var(--ssml-editor-control-border)",
    borderRadius: "0.25rem",
    backgroundColor: "var(--ssml-editor-control-bg)",
    boxShadow: "0 0.25rem 0.75rem rgb(0 0 0 / 20%)",
    overflowY: "auto",
  },
  toolbarOption: {
    padding: "0.375rem 0.5rem",
    border: 0,
    borderRadius: "0.125rem",
    color: "var(--ssml-editor-color)",
    backgroundColor: "transparent",
    font: "inherit",
    textAlign: "left",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  toolbarOptionGroup: {
    display: "grid",
    gap: "0.125rem",
    margin: 0,
    padding: 0,
    border: 0,
  },
  toolbarOptionGroupLabel: {
    padding: "0.375rem 0.5rem 0.125rem",
    color: "var(--ssml-editor-color)",
    fontSize: "0.875rem",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  toolbarEmpty: {
    margin: 0,
    padding: "0.375rem 0.5rem",
    color: "var(--ssml-editor-color)",
    whiteSpace: "nowrap",
  },
  toolbarEmptySelect: {
    padding: "0.375rem 0.5rem",
    border: "1px solid var(--ssml-editor-control-border)",
    borderRadius: "0.125rem",
    color: "var(--ssml-editor-color)",
    backgroundColor: "var(--ssml-editor-control-bg)",
    font: "inherit",
    textAlign: "left",
  },
  helpPanel: {
    display: "grid",
    gap: "0.5rem",
    width: "100%",
    padding: "0.75rem",
    border: "1px solid var(--ssml-editor-control-border)",
    borderRadius: "0.25rem",
    backgroundColor: "var(--ssml-editor-preview-bg)",
  },
  helpHeading: {
    margin: 0,
    fontSize: "1rem",
  },
  helpDescription: {
    margin: 0,
    lineHeight: 1.5,
  },
  helpList: {
    display: "grid",
    gap: "0.375rem",
    margin: 0,
    paddingLeft: "1.25rem",
  },
  helpItem: {
    listStyleType: "none",
    lineHeight: 1.45,
  },
  helpIcon: {
    display: "inline-flex",
    width: "1.25rem",
    justifyContent: "center",
    fontSize: "1.1rem",
    lineHeight: 1.45,
  },
  helpSettingsAccordion: {
    marginTop: "0.375rem",
    overflow: "hidden",
    border: "1px solid var(--ssml-editor-control-border)",
    borderRadius: "0.25rem",
    backgroundColor: "var(--ssml-editor-control-bg)",
  },
  helpSettingsSummary: {
    display: "grid",
    gridTemplateColumns: "1rem 1.25rem minmax(0, 1fr)",
    columnGap: "0.5rem",
    alignItems: "start",
    padding: "0.5rem 0.625rem",
    cursor: "pointer",
  },
  helpSettingsSummaryContent: {
    minWidth: 0,
  },
  helpSettingsDescription: {
    margin: "0.5rem 0.75rem 0",
    fontSize: "0.875rem",
  },
  helpSettingsList: {
    display: "grid",
    gap: "0.125rem",
    margin: "0.25rem 0.75rem 0.75rem",
    paddingLeft: "1.25rem",
    fontSize: "0.875rem",
  },
  editor: {
    boxSizing: "border-box",
    position: "relative",
    width: "100%",
    minHeight: "8rem",
    border: "1px solid var(--ssml-editor-control-border)",
    borderRadius: "0.25rem",
    overflow: "visible",
  },
  selectionActions: {
    position: "absolute",
    zIndex: OVERLAY_Z_INDEX,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "0.25rem",
    maxWidth: "calc(100% - 1rem)",
    padding: "0.25rem",
    border: "1px solid var(--ssml-editor-control-border)",
    borderRadius: "0.375rem",
    color: "var(--ssml-editor-color)",
    backgroundColor: "var(--ssml-editor-control-bg)",
    boxShadow: "0 0.25rem 0.75rem rgb(0 0 0 / 20%)",
  },
  selectionCount: {
    padding: "0.25rem 0.375rem",
    fontSize: "0.875rem",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  selectionActionsDivider: {
    width: "1px",
    height: "1.5rem",
    backgroundColor: "var(--ssml-editor-border)",
  },
  selectionActionButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.25rem",
    minHeight: "1.75rem",
    padding: "0.25rem 0.375rem",
    border: "1px solid var(--ssml-editor-control-border)",
    borderRadius: "0.25rem",
    color: "var(--ssml-editor-color)",
    backgroundColor: "var(--ssml-editor-bg)",
    font: "inherit",
    fontSize: "0.875rem",
    cursor: "pointer",
  },
  selectionActionIcon: {
    display: "inline-flex",
    width: "1rem",
    justifyContent: "center",
    lineHeight: 1,
  },
  error: {
    margin: 0,
    padding: "0.5rem 0.75rem",
    border: "1px solid var(--ssml-editor-error)",
    borderRadius: "0.25rem",
    color: "var(--ssml-editor-error)",
    backgroundColor: "var(--ssml-editor-error-bg)",
    lineHeight: 1.5,
  },
};
