export const DEFAULT_LOCALE = "ja" as const;
export const OVERLAY_Z_INDEX = 9999;
export const TOOLBAR_MENU_Z_INDEX = OVERLAY_Z_INDEX;
export const SELECTION_ACTIONS_Z_INDEX = OVERLAY_Z_INDEX;
export const SELECTION_OVERLAY_ABOVE_THRESHOLD_LINES = 4;
