import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join, resolve } from "node:path";

export interface AzureVoiceApiVoice {
  Locale?: unknown;
  Name?: unknown;
  SecondaryLocaleList?: unknown;
  ShortName?: unknown;
  StyleList?: unknown;
}

export interface AzureVoiceDefinitionRecord {
  locale: string;
  name: string;
  secondaryLocales?: string[];
  styles?: string[];
}

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CORE_OUTPUT = join(ROOT, "packages", "ssml-core", "src", "generated", "azureVoiceDefinitions.ts");
const EDITOR_OUTPUT = join(
  ROOT,
  "packages",
  "ssml-editor-react",
  "src",
  "constants",
  "azureVoiceStyleMap.generated.ts",
);

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

function stringList(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return [...new Set(value.map(stringValue).filter((item): item is string => item !== undefined))];
}

export function normalizeAzureVoices(payload: unknown): AzureVoiceDefinitionRecord[] {
  if (!Array.isArray(payload)) throw new Error("Azure voices response must be a JSON array.");

  const byName = new Map<string, AzureVoiceDefinitionRecord>();
  for (const item of payload as AzureVoiceApiVoice[]) {
    if (!item || typeof item !== "object") continue;
    const name = stringValue(item.ShortName) ?? stringValue(item.Name);
    const locale = stringValue(item.Locale);
    if (!name || !locale) continue;
    const secondaryLocales = stringList(item.SecondaryLocaleList);
    const styles = stringList(item.StyleList);
    const definition: AzureVoiceDefinitionRecord = {
      name,
      locale,
      ...(secondaryLocales.length > 0 ? { secondaryLocales } : {}),
      ...(styles.length > 0 ? { styles } : {}),
    };
    const key = name.toLowerCase();
    if (!byName.has(key)) byName.set(key, definition);
  }

  return [...byName.values()].sort((first, second) => first.name.localeCompare(second.name));
}

function renderCoreDefinitions(definitions: readonly AzureVoiceDefinitionRecord[]): string {
  return [
    "/** Generated by scripts/sync-azure-voices.ts. */",
    'import type { AzureVoiceDefinition } from "../azureValidation.ts";',
    "",
    `export const AZURE_VOICE_DEFINITIONS: readonly AzureVoiceDefinition[] = ${JSON.stringify(definitions, null, 2)};`,
    "",
  ].join("\n");
}

function renderEditorStyleMap(definitions: readonly AzureVoiceDefinitionRecord[]): string {
  const styles = Object.fromEntries(definitions.map((definition) => [definition.name, definition.styles ?? []]));
  return [
    "/** Generated by scripts/sync-azure-voices.ts. */",
    `export const AZURE_VOICE_STYLE_MAP = ${JSON.stringify(styles, null, 2)} as const satisfies Readonly<Record<string, readonly string[]>>;`,
    "",
  ].join("\n");
}

async function fetchAzureVoices(region: string, key: string): Promise<unknown> {
  const endpoint = `https://${region}.tts.speech.microsoft.com/cognitiveservices/voices/list`;
  const response = await fetch(endpoint, { headers: { "Ocp-Apim-Subscription-Key": key } });
  if (!response.ok) throw new Error(`Azure List Voices API request failed with HTTP ${response.status}.`);
  return response.json();
}

interface CliOptions {
  dryRun: boolean;
  inputPath?: string;
  key?: string;
  region?: string;
}

function parseArgs(args: readonly string[]): CliOptions {
  const options: CliOptions = { dryRun: false };
  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === "--dry-run") options.dryRun = true;
    else if (argument === "--region") options.region = args[++index];
    else if (argument === "--key") options.key = args[++index];
    else if (argument === "--input") options.inputPath = args[++index];
    else throw new Error(`Unknown option: ${argument}`);
  }
  return options;
}

export async function syncAzureVoices(options: CliOptions): Promise<AzureVoiceDefinitionRecord[]> {
  const payload = options.inputPath
    ? JSON.parse(await readFile(resolve(options.inputPath), "utf8"))
    : await fetchAzureVoices(
        options.region ?? process.env.AZURE_SPEECH_REGION ?? "",
        options.key ?? process.env.AZURE_SPEECH_KEY ?? "",
      );
  const definitions = normalizeAzureVoices(payload);
  if (definitions.length === 0) throw new Error("Azure List Voices API returned no usable voice definitions.");
  if (!options.dryRun) {
    await writeFile(CORE_OUTPUT, renderCoreDefinitions(definitions), "utf8");
    await writeFile(EDITOR_OUTPUT, renderEditorStyleMap(definitions), "utf8");
  }
  return definitions;
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  const region = options.region ?? process.env.AZURE_SPEECH_REGION;
  const key = options.key ?? process.env.AZURE_SPEECH_KEY;
  if (!options.inputPath && (!region || !key))
    throw new Error("Set AZURE_SPEECH_REGION and AZURE_SPEECH_KEY, or pass --region and --key.");
  const definitions = await syncAzureVoices(options);
  console.log(`${options.dryRun ? "Found" : "Updated"} ${definitions.length} Azure voice definitions.`);
}

const currentScript = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (currentScript === import.meta.url) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
