export const SYNTHESIS_NAMESPACE = "http://www.w3.org/2001/10/synthesis" as const;
export const MSTTS_NAMESPACE = "http://www.w3.org/2001/mstts" as const;
export const DEFAULT_SSML_VERSION = "1.0" as const;
export const DEFAULT_SSML_LANGUAGE = "en-US" as const;
export const MAX_NESTING_DEPTH = 1000;
export const XML_NAME_PATTERN = /^[A-Za-z_][A-Za-z0-9_.:-]*$/;
export const MSTTS_TAG_PREFIX = "mstts:" as const;

export const SSML_TAGS = {
  SPEAK: "speak",
  VOICE: "voice",
  PROSODY: "prosody",
  BREAK: "break",
  EXPRESS_AS: "express-as",
  EXPRESS_AS_CAMEL: "expressAs",
  MSTTS_EXPRESS_AS: "mstts:express-as",
  SAY_AS: "say-as",
  SAY_AS_CAMEL: "sayAs",
  PHONEME: "phoneme",
  EMPHASIS: "emphasis",
  AUDIO: "audio",
  SUB: "sub",
  LANG: "lang",
  MARK: "mark",
  BOOKMARK: "bookmark",
  LEXICON: "lexicon",
  PARAGRAPH: "p",
  SENTENCE: "s",
  WORD: "w",
  MSTTS_SILENCE: "mstts:silence",
  SILENCE: "silence",
  MSTTS_VISEME: "mstts:viseme",
  VISEME: "viseme",
} as const;

export const SSML_ATTRS = {
  VERSION: "version",
  XMLNS: "xmlns",
  XML_LANG: "xml:lang",
  LANG: "lang",
  MSTTS_XMLNS: "xmlns:mstts",
  NAME: "name",
  EFFECT: "effect",
  RATE: "rate",
  PITCH: "pitch",
  VOLUME: "volume",
  CONTOUR: "contour",
  RANGE: "range",
  TIME: "time",
  STRENGTH: "strength",
  STYLE: "style",
  STYLE_DEGREE: "styledegree",
  STYLE_DEGREE_CAMEL: "styleDegree",
  ROLE: "role",
  INTERPRET_AS: "interpret-as",
  FORMAT: "format",
  DETAIL: "detail",
  ALPHABET: "alphabet",
  PH: "ph",
  LEVEL: "level",
  SRC: "src",
  DESC: "desc",
  CLIP_BEGIN: "clipBegin",
  CLIP_END: "clipEnd",
  SPEED: "speed",
  REPEAT_COUNT: "repeatCount",
  REPEAT_DURATION: "repeatDuration",
  SOUND_LEVEL: "soundLevel",
  ALIAS: "alias",
  MARK: "mark",
  URI: "uri",
  TYPE: "type",
  VALUE: "value",
} as const;
